export const moduleConstants = {
  dashboard: 'dashboard',
  applicationUsers: 'applicationUsers',
  business: 'business',
  businessSales: 'businessSales',
  appHomePage: 'appHomePage',
  nirlatTeams: 'nirlatTeams',
  businessCard: 'businessCard',
  productList: 'productList',
  scannedInvoices: 'scannedInvoices',
  colorFans: 'colorFans',
  colorCombination: 'colorCombination',
  nirlatConsultation: 'nirlatConsultation',
  nirlatPromotions: 'nirlatPromotions',
  buyMeOrders: 'buyMeOrders',
  nirlatGiftOrders: 'nirlatGiftOrders',
  nirlatGifts: 'nirlatGifts',
  appDictionary: 'appDictionary',
  onBoardingScreens: 'onBoardingScreens',
  appContents: 'appContents',
  generalSettings: 'generalSettings',
  pushNotification: 'pushNotification',
  pointManagement: 'pointManagement',
  eventRegistration: 'eventRegistration',
  systemAdmins: 'systemAdmins',
};
