import { MOODANDEMOTIONTYPE } from './enums';

export const moodAndEmotionValue = {
  [MOODANDEMOTIONTYPE.VERY_PLEASANT]: 7,
  [MOODANDEMOTIONTYPE.SLIGHTLY_PLEASANT]: 6,
  [MOODANDEMOTIONTYPE.PLEASANT]: 5,
  [MOODANDEMOTIONTYPE.NEUTRAL]: 4,
  [MOODANDEMOTIONTYPE.UNPLEASANT]: 3,
  [MOODANDEMOTIONTYPE.SLIGHTLY_UNPLEASANT]: 2,
  [MOODANDEMOTIONTYPE.VERY_UNPLEASANT]: 1,
};
